### PR TITLE
mz -> fs-extra

### PR DESCRIPTION
**Pull request by jdxcode**
mz is showing a deprecation warning right now in node 10

### CODE REVIEW

**Comment by xavdid** [comment]
Hey Jeff! Thanks for the contribution. This looks like a good change since `fs-extra` seems to be better maintained than `mz`. I'll also have the chance to bump some deps. 

I'm just curious before I merge - what deprecation warning are you seeing? I just installed w/ node `10.1.0` and npm `6.0.1` and didn't see any warnings out of the ordinary.

**Comment by jdxcode** [comment]
if you run `heroku plugins:install heroku-config` and are on the latest version of the CLI it should display the warning, it says "The fs.promises API is experimental"

**Comment by xavdid** [comment]
Ah, got it. Looks like that's a [known issue](https://github.com/normalize/mz/issues/63#issuecomment-388092836) in node and will get fixed in `10.1.1` or `10.2.0`. Still happy to change here (there's some other housekeeping I need to do anyway) but if that's releasing soon and you're upgrading to it, the warning should disappear.

**Comment by jdxcode** [comment]
good to know! we've been getting reports of this in various plugins and we generally use `fs-extra` in all of our code anyways so I've just converting it

**Comment by xavdid** [comment]
Totally. I'll grab today or tomorrow and get it released.

**Comment by xavdid** [comment]
deployed! 

As a side note, I noticed there aren't any changelogs for `heroku-cli-util`. This depends on the last version of 6. It seems like there's nothing majorly breaking, but I didn't feel confident upping across a semver major without knowing what was the reason for the break

**Comment by jdxcode** [comment]
the major bump there was because we updated the version of got used. You're not using that so it's safe to update. `heroku-cli-util` is effectively deprecated now though. `heroku-cli-util` and this plugin is in the older syntax we used before we came out with oclif which works quite a bit differently.

No need to change this plugin though, it will be supported for the forseeable future (we're not changing any of our code to be oclif—just writing new stuff in oclif)

**Comment by xavdid** [comment]
Got it. I'll bump to latest and leave as is for now. If it ever gets deprecated, i'll deal with it then.

**Comment by jdxcode** [comment]
that's probably at least 2-3 years out I'd say

**Pull request merged**
